### ISSUE TITLE
Dtuch GTFS data seems to have different lay-out?

### ISSUE THREAD

**Issue by Flight777** [jarondl/pygtfs#26]
Hi,

Indirectly I'm trying to get your awesome piece of software to work as it was implemented in Home-Assistant :D I'm trying to add the GTFS data for The Netherlands, however, it seems to have some format issues. Could you confirm? The official data is here: http://gtfs.ovapi.nl/new/gtfs-nl.zip

The following error log pops up in home-assistant:

`16-04-13 20:21:49 homeassistant.components.sensor: Error while setting up platform gtfs
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/helpers/entity_component.py", line 91, in _setup_platform
    discovery_info)
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/sensor/gtfs.py", line 157, in setup_platform
    config["origin"], config["destination"]))
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/sensor/gtfs.py", line 176, in __init__
    self.update()
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/sensor/gtfs.py", line 215, in update
    self._data_source))
  File "/home/rob/.homeassistant/lib/pygtfs/loader.py", line 87, in append_feed
    instance = gtfs_class(feed_id=feed_id, **records_as_dict)
  File "<string>", line 4, in __init__
  File "/home/rob/.homeassistant/lib/sqlalchemy/orm/state.py", line 306, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/home/rob/.homeassistant/lib/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/rob/.homeassistant/lib/sqlalchemy/util/compat.py", line 184, in reraise
    raise value
  File "/home/rob/.homeassistant/lib/sqlalchemy/orm/state.py", line 303, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/home/rob/.homeassistant/lib/sqlalchemy/ext/declarative/base.py", line 649, in _declarative_constructor
    setattr(self, k, kwargs[k])
  File "/home/rob/.homeassistant/lib/sqlalchemy/orm/attributes.py", line 224, in __set__
    instance_dict(instance), value, None)
  File "/home/rob/.homeassistant/lib/sqlalchemy/orm/attributes.py", line 701, in set
    value, old, initiator)
  File "/home/rob/.homeassistant/lib/sqlalchemy/orm/attributes.py", line 710, in fire_replace_event
    self._init_append_or_replace_token())
  File "/home/rob/.homeassistant/lib/sqlalchemy/orm/util.py", line 118, in set_
    return validator(state.obj(), key, value)
  File "/home/rob/.homeassistant/lib/pygtfs/gtfs_entities.py", line 57, in in_range
    raise ValueError("Empty value not allowed in {0}".format(key))
ValueError: Empty value not allowed in wheelchair_boarding`

Thanks so much! :+1: 

Rob

**Comment by jarondl** [comment]
Hi Rob,
The dutch have it right. This is the same issue as #23, which was fixed very recently in the master branch.
I plan to release version 0.2.0 shortly, so the PyPI version will also be corrected.

**Comment by Flight777** [comment]
Thanks for the fast reply and very good to hear! Eagerly awaiting the update, then my girlfriend won't be late for her bus again haha

Thanks for sharing this with the world :+1:

**Comment by jarondl** [comment]
Fixed in 0.1.3
