### ISSUE TITLE
Getting validation error during the bootstrap for `location_type` not recognized

### ISSUE THREAD

**Issue by mazzy89** [jarondl/pygtfs#59]
I'm getting the following error:

```
Logger: homeassistant.components.sensor
Source: components/gtfs/sensor.py:511
Integration: Sensor (documentation, issues)
First occurred: 7:28:50 PM (1 occurrences)
Last logged: 7:28:50 PM

Error while setting up gtfs platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 231, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/gtfs/sensor.py", line 511, in setup_platform
    pygtfs.append_feed(gtfs, os.path.join(gtfs_dir, data))
  File "/usr/local/lib/python3.8/site-packages/pygtfs/loader.py", line 81, in append_feed
    instance = gtfs_class(feed_id=feed_id, **record._asdict())
  File "<string>", line 4, in __init__
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/state.py", line 445, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/state.py", line 442, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/decl_base.py", line 1145, in _declarative_constructor
    setattr(self, k, kwargs[k])
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 458, in __set__
    self.impl.set(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 1070, in set
    value = self.fire_replace_event(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 1078, in fire_replace_event
    value = fn(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/util.py", line 185, in set_
    return validator(state.obj(), key, value)
  File "/usr/local/lib/python3.8/site-packages/pygtfs/gtfs_entities.py", line 65, in in_range
    raise PygtfsValidationError(
pygtfs.exceptions.PygtfsValidationError: location_type must be in range [None, 0, 1, 2], was 3
```

because the following GTFS file http://data.pid.cz/PID_GTFS.zip has `location_type` set to 3.

**Comment by mazzy89** [comment]
This has been merged. closing.
